version: '2'
services:
  webserver-DB:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=myDB
  webserver:
    image: mandaliya/php8-apache
#    image: sikessem/php8-apache

    ports:
      - "80:80"
    depends_on:
      - webserver-DB
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internaltouch